services:
  db:
    container_name: db_crud
    image: postgres:16.2
    restart : on-failure
    ports:
      - 5432:5432
   #volumes:
   #  - ~/apps/postgres:/var/lib/postgresql/data
   #  - ./config/db_crud.sql:/docker-entrypoint-initdb.d/backup.sql
    environment:
      - POSTGRES_PASSWORD=pass_crud
      - POSTGRES_USER=user_crud
      - POSTGRES_DB=db_crud
    networks:
      - crudreverse
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_db_crud
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user_crud@postgres.com
      PGADMIN_DEFAULT_PASSWORD: pass_crud
    depends_on:
        - db
    networks:
      - crudreverse
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./minio/volume:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: always
  backend:
    # image: node
    container_name: backend-nestjs-crud
    build: ./backend
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    ports:
      - "8080:3000"
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - db
    networks:
      - crudreverse
  #frontend:
  #  container_name: frontend-vuejs-crud
  #  build: ./frontend
  #  volumes:
  #    - './frontend:/app'
  #    - '/app/node_modules'
  #  tty: true
  #  ports:
  #    - '5173:5173'
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
  #    - WATCHPACK_POLLING=true
  #    - TZ=Asia/Bangkok
  #  stdin_open: true
  #  depends_on:
  #    - db
  #    - backend
  #  networks:
  #    - crudreverse
  #nginx:
  #  container_name: crudproxy
  #  build: ./nginx_crudproxy
  #  image: nginx:latest
  #  ports:
  #    - 80:80
  #  depends_on:
  #    #- frontend
  #    - backend
  #  networks:
  #    - crudreverse
networks:
  crudreverse:
    driver: bridge

  